AppReception/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from hsm.chess import ChessViews
from hsm.views import EditServicesViews, \
    checks_list, \
    print_booking, \
    organization, \
    add_guest, \
    HomeViews, \
    profile, \
    statistics, \
    TasksViews, \
    GuestsViews, \
    BookingViews, \
    StatusBookingViews, \
    EditBookingViews, \
    DetailBookingViews, \
    user_login, \
    user_logout, \
    user_register, \
    ListBookingViews, \
    printer, \
    ListServicesViews, \
    CreateServicesViews
from hsm.new_chess import NewChessViews

admin.site.site_header = 'Панель управления'
urlpatterns = [
                  path('', HomeViews.as_view(), name='home'),
                  path('chess/', ChessViews.as_view(), name='chess'),
                  path('print/<str:_date>', printer, name='print'),
                  path('admin/', admin.site.urls),
                  path('checks/', checks_list, name='checks-list'),
                  path('login/', user_login, name='login'),
                  path('logout/', user_logout, name='logout'),
                  path('register/', user_register, name='register'),
                  path('booking/', BookingViews.as_view(), name='booking'),
                  path('booking/print-<int:id>', print_booking, name='booking-print'),
                  path('guests/', GuestsViews.as_view(), name='guests'),
                  path('guests/add/', add_guest, name='guest-add'),
                  path('bookings/', ListBookingViews.as_view(), name='list-booking'),
                  path('organization/', organization, name='organization'),
                  path('tasks/', TasksViews.as_view(), name='tasks'),
                  path('statistics/', statistics, name='statistics'),
                  path('services/list', ListServicesViews.as_view(), name='services-list'),
                  path('services/edit-<int:pk>', EditServicesViews.as_view(), name='services-edit'),
                  path('services/create', CreateServicesViews.as_view(), name='services-create'),
                  path('profile/', profile, name='profile'),
                  path('new-chess/', NewChessViews.as_view(), name='new-chess'),
                  path('ajax/', include('hsm.urls'), name='ajax'),
                  path('booking/edit-<int:id>', EditBookingViews.as_view(), name='edit-booking'),
                  path('booking/detail-<int:id>', DetailBookingViews.as_view(), name='detail-booking'),
                  path('booking/status-<int:id>', StatusBookingViews.as_view(), name='status-booking'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hsm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from hsm.ajax import ajax_services_info, ajax_check_print, ajax_bookings_extend, ajax_bookings_change, \
    ajax_search_booking_id, ajax_send_booking_group, ajax_evict_send, ajax_guest_add, ajax_booking_info, ajax_new_chess, \
    ajax_search_rooms, ajax_info_type_rooms, ajax_booking_post, ajax_search_guest, \
    ajax_status_booking_change, ajax_status_booking_remove, ajax_today_date, ajax_cleaning

app_name = 'ajax'
urlpatterns = [
    path('today-date/', ajax_today_date, name='ajax-today-date'),
    path('evict-send/', ajax_evict_send, name='ajax-evict-send'),
    path('cleaning/', ajax_cleaning, name='ajax-cleaning'),
    path('booking-info/', ajax_booking_info, name='ajax-booking-info'),
    path('services-info/', ajax_services_info, name='ajax-services-info'),
    path('bookings-change/', ajax_bookings_change, name='ajax-bookings-change'),
    path('bookings-extend/', ajax_bookings_extend, name='ajax-bookings-extend'),
    path('send-booking-group/', ajax_send_booking_group, name='ajax-send-booking-group'),
    path('search-booking-id/', ajax_search_booking_id, name='ajax-search-booking-id'),
    path('new-chess/', ajax_new_chess, name='ajax-new-chess'),
    path('check-print/', ajax_check_print, name='ajax-check-print'),
    path('status-booking-change/', ajax_status_booking_change, name='ajax-status-booking-change'),
    path('status-booking-remove/', ajax_status_booking_remove, name='ajax-status-booking-remove'),
    path('search-guest/', ajax_search_guest, name='ajax-search-guest'),
    path('booking-post/', ajax_booking_post, name='ajax-booking-post'),
    path('guest-add/', ajax_guest_add, name='ajax-guest-add'),
    path('search-rooms/', ajax_search_rooms, name='ajax-search-rooms'),
    path('info-type-rooms/', ajax_info_type_rooms, name='ajax-info-type-rooms'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hsm/models.py
import arrow
from django.contrib import admin
from django.contrib.auth.models import User
from django.db import models


# Типы номеров
class TypeRoom(models.Model):
    name = models.CharField(verbose_name='Тип комнаты', max_length=50, blank=True)
    price_uzs = models.DecimalField(verbose_name='Цена комнаты для граждан РУЗ', max_digits=8, decimal_places=0,
                                    null=True, blank=True)
    price_usd = models.DecimalField(verbose_name='Цена комнаты для иностранцев', max_digits=8, decimal_places=0,
                                    null=True, blank=True)

    class Meta:
        verbose_name = 'Тип комнаты'
        verbose_name_plural = 'Типы комнат'

    def __str__(self):
        return self.name


# Имя номеров
class Rooms(models.Model):
    type_room = models.ForeignKey(TypeRoom, verbose_name='Тип комнаты', on_delete=models.CASCADE)
    number_room = models.CharField(verbose_name='Номер комнаты', max_length=50, blank=True)
    close = models.BooleanField(verbose_name='Закрыть номер', default=False)
    clean = models.BooleanField(verbose_name='Статус номера', default=True)

    class Meta:
        verbose_name = 'Номер комнаты'
        verbose_name_plural = 'Номера комнат'

    def __str__(self):
        return '%s-%s' % (self.type_room.name, self.number_room)


# Метки
class Tag(models.Model):
    name = models.CharField(verbose_name='Тег', max_length=50)

    class Meta:
        verbose_name_plural = 'Теги'
        verbose_name = 'Тег'

    def __str__(self):
        return self.name


# Страны, города
class City(models.Model):
    name = models.CharField(verbose_name="Город", max_length=50)

    class Meta:
        verbose_name = 'Страна'
        verbose_name_plural = 'Страны'

    def __str__(self):
        return self.name


admin.site.register(City)


# Национальность
class Nationality(models.Model):
    name = models.CharField(verbose_name="Национальность", max_length=50)

    class Meta:
        verbose_name = 'Национальность'
        verbose_name_plural = 'Национальности'

    def __str__(self):
        return self.name


admin.site.register(Nationality)


# Данные визы
class Visa(models.Model):
    number = models.CharField(verbose_name="номер", max_length=50)
    visa_type = models.CharField(verbose_name="тип", max_length=50)
    given_date = models.CharField(verbose_name="Дата выдачи", max_length=30)
    expire_date = models.CharField(verbose_name="Дата окончания срока", max_length=30)

    class Meta:
        verbose_name = 'Виза'
        verbose_name_plural = 'Визы'

    def __str__(self):
        return self.number


admin.site.register(Visa)


# Гражданство
class Citeznship(models.Model):
    name = models.CharField(verbose_name='Гражданство', max_length=50)

    class Meta:
        verbose_name = 'Гражданство'
        verbose_name_plural = 'Гражданства'

    def __str__(self):
        return self.name


# Данные гостя
class Guest(models.Model):
    full_name = models.CharField(verbose_name='Ф.И.О', max_length=100, unique=True)
    phone = models.CharField(verbose_name='Телефон', max_length=50, blank=True)
    email = models.EmailField(verbose_name='Email', max_length=50, blank=True)
    passport = models.BooleanField(verbose_name='Паспорт в наличии', default=True)
    date_of_birth = models.CharField(verbose_name='Дата рождения', max_length=50, blank=True)
    place_of_birth = models.ForeignKey(City, verbose_name="Место рождение: город", on_delete=models.CASCADE, null=True,
                                       blank=True)
    serial_number = models.CharField(verbose_name="Серийный номер паспорта", max_length=50, blank=True)
    given_date = models.CharField(verbose_name="Дата выдачи паспорта", max_length=30, blank=True)
    expire_date = models.CharField(verbose_name="Дата окончания срока паспорта", max_length=30, blank=True)
    give_organization = models.CharField(verbose_name="Кем выдано", max_length=100, blank=True)
    place_of_living = models.CharField(verbose_name="Место проживания", max_length=100, blank=True)
    nationality = models.ForeignKey(Nationality, verbose_name="Национальность", on_delete=models.CASCADE, null=True,
                                    blank=True)
    citeznship = models.ForeignKey(Citeznship, verbose_name="Гражданство", on_delete=models.CASCADE, null=True,
                                   blank=True)
    kpp_number = models.CharField(verbose_name='КПП №', max_length=50, blank=True)
    kpp_date_arrival = models.CharField(verbose_name='Дата заезда КПП', max_length=30, blank=True)
    visa = models.ForeignKey(Visa, verbose_name="VISA", on_delete=models.CASCADE, blank=True, null=True)

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'

    def __str__(self):
        return self.full_name


admin.site.register(Guest)


# Источник откуда поступила бронь
class SourceBooking(models.Model):
    name = models.CharField(verbose_name='Источник бронирования', max_length=50)

    class Meta:
        verbose_name_plural = 'Источники брони'
        verbose_name = 'Источник брони'

    def __str__(self):
        return self.name


admin.site.register(SourceBooking)


# Задачи
class Task(models.Model):
    title = models.CharField(verbose_name='Что сделать', max_length=50, blank=True)
    info = models.TextField(verbose_name='Описание', blank=True)
    # alarm = models.IntegerField(verbose_name='Когда выполнить', null=True, blank=True)
    datetime = models.DateTimeField(verbose_name='Дата и время напоминания', null=True, blank=True)
    status = models.BooleanField(verbose_name='Выполнено', default=False)

    class Meta:
        verbose_name = 'Задача'
        verbose_name_plural = 'Задачи'

    def __str__(self):
        return self.title


admin.site.register(Task)


class Organization(models.Model):
    name = models.CharField(verbose_name='Оргазинация', max_length=100, blank=True)

    class Meta:
        verbose_name = 'Организация'
        verbose_name_plural = 'Организации'

    def __str__(self):
        return self.name


admin.site.register(Organization)


# Информация бронирования
class Booking(models.Model):
    EMPTY = 0
    BOOKING_NOT_PAYMENT = -1
    BOOKING_PAYMENT = 1
    QUEST_ACCOMMODATION_NOT_PAYMENT = -2
    QUEST_ACCOMMODATION_PAYMENT = 2
    EVICTED_ACCOMMODATION = -3
    RESERVE = 3
    GUEST_LEAVE_TODAY = 4
    BLOCKING_ROOM = -4

    STATUS_BOOKING = (
        (EMPTY, 'Пусто'),
        (BOOKING_NOT_PAYMENT, 'Бронь без оплаты'),
        (BOOKING_PAYMENT, 'Бронь с предоплатой'),
        (QUEST_ACCOMMODATION_NOT_PAYMENT, 'Размещение гостя с долгом'),
        (QUEST_ACCOMMODATION_PAYMENT, 'Размещение гостя с оплатой'),
        (EVICTED_ACCOMMODATION, 'Выселенное размещение'),
        (RESERVE, 'Резерв'),
        (GUEST_LEAVE_TODAY, 'Гости сегодня выезжают'),
        (BLOCKING_ROOM, 'Блокировка номера'),
    )

    A = 0
    B = 1
    C = 2
    D = 3
    E = 4
    TYPE_PAYMENT = (
        (A, 'Не известно'),
        (B, 'Наличка'),
        (C, 'Пластик'),
        (D, 'Перечисление'),
        (E, 'В долларах')
    )

    date_arrival = models.DateTimeField(verbose_name='Дата и время заезда', null=True, blank=True)
    early_arrival = models.BooleanField(verbose_name='Ранний заезд', default=False)
    date_departure = models.DateTimeField(verbose_name='Дата и время выезда', null=True, blank=True)
    late_departure = models.BooleanField(verbose_name='Поздник заезд', default=False)
    price_per_night = models.DecimalField(verbose_name='Цена за ночь', max_digits=10, decimal_places=0, default=0)
    price_for_all_time = models.DecimalField(verbose_name='Цена за всё время', max_digits=10, decimal_places=0,
                                             default=0)
    payment_nal = models.DecimalField(verbose_name='Сумма - налом', max_digits=10, decimal_places=0, default=0)
    payment_bez_nal = models.DecimalField(verbose_name='Сумма - перечисление', max_digits=10, decimal_places=0,
                                          default=0)
    payment_terminal = models.DecimalField(verbose_name='Сумма - терминал', max_digits=10, decimal_places=0, default=0)
    payment_usd = models.DecimalField(verbose_name='Сумма - в долларах', max_digits=10, decimal_places=0, default=0)
    paid = models.DecimalField(verbose_name='Оплачено', max_digits=10, decimal_places=0, default=0)
    left_to_pay = models.DecimalField(verbose_name='Осталось оплатить', max_digits=10, decimal_places=0, default=0)
    days = models.FloatField(verbose_name='Суток', null=True, blank=True)
    status_booking = models.IntegerField(verbose_name='Статус брони', choices=STATUS_BOOKING, default=EMPTY)

    user = models.ForeignKey(User, verbose_name='Администратор', on_delete=models.CASCADE, null=True, blank=True)
    guest = models.ManyToManyField(Guest, verbose_name='Проживающие гости', blank=True)
    organization = models.ForeignKey(Organization, verbose_name='Организация', on_delete=models.CASCADE, null=True,
                                     blank=True)
    room = models.ForeignKey(Rooms, verbose_name='Номер остановки', on_delete=models.CASCADE, null=True, blank=True)
    task = models.ForeignKey(Task, verbose_name='Задачи', on_delete=models.CASCADE, null=True, blank=True)
    source_of_booking = models.ForeignKey(SourceBooking, verbose_name='Источник бронирования', on_delete=models.CASCADE,
                                          null=True, blank=True)
    number_source_booking = models.CharField(verbose_name='Номер брони источника', max_length=50, blank=True)
    admin_comment = models.TextField(verbose_name='Комментарий администратора', blank=True)
    customer_wishes = models.TextField(verbose_name='Пожелания гостя', blank=True)

    stat = models.BooleanField(verbose_name='Состояние брони/объекта', default=True)

    class Meta:
        verbose_name = 'Бронь'
        verbose_name_plural = 'Брони'

    def save(self, *args, **kwargs):

templates/guests/add-guest.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/guest-add.css' %}">
{% endblock %}

{% block title %}
    База клиентов
{% endblock %}

{% block content %}
    <form action="." method="post">{% csrf_token %}
        <div style="display: flex; align-items: end; background-color: #fff; padding: 10px; margin:15px 0">
            <div class="guest-form">

                <label for="id_fullname">Ф.И.О</label>
                <input type="text" name="fullname" id="id_fullname"
                       autocomplete="off">

                <label for="id_date_of_birth">Дата рождения</label>
                <input type="text" name="date_of_birth" id="id_date_of_birth"
                       autocomplete="off">

                <label for="id_serial_number">Серийный номер паспорта</label>
                <input type="text" name="serial_number" id="id_serial_number"
                       autocomplete="off">

                <label for="id_given_date">Дата выдачи паспорта</label>
                <input type="text" name="given_date" id="id_given_date"
                       autocomplete="off">

                <label for="id_expire_date">Дата окончания срока паспорта</label>
                <input type="text" name="expire_date" id="id_expire_date"
                       autocomplete="off">

                <label for="id_give_organization">Кем выдано</label>
                <input type="text" name="give_organization"
                       id="id_give_organization"
                       autocomplete="off">

                <label for="id_place_of_living">Место проживания</label>
                <input type="text" name="place_of_living" id="id_place_of_living"
                       autocomplete="off">

                <label for="id_nationality">Национальность</label>
                <select name="nationality" id="id_nationality"
                        class="js-example-single">
                    {% for nationality in form_guest.nationality %}
                        {{ nationality }}
                    {% endfor %}
                </select>

                <label for="id_citeznship">Гражданство</label>
                <select name="citeznship" id="id_citeznship">
                    {% for citeznship in form_guest.citeznship %}
                        {{ citeznship }}
                    {% endfor %}
                </select>

            </div>
            <div class="guest-form">

                <label for="id_phone">Телефон:</label>
                <input type="text" name="phone" id="id_phone" autocomplete="off">

                <label for="id_email">Email:</label>
                <input type="text" name="email" id="id_email">

                <label for="id_kpp_number">КПП №</label>
                <input type="text" name="kpp_number" id="id_kpp_number"
                       autocomplete="off">

                <label for="id_kpp_date_arrival">Дата заезда КПП</label>
                <input type="text" name="kpp_date_arrival" id="id_kpp_date_arrival"
                       autocomplete="off">

                <hr>
                <hr>

                <label for="id_visa">Виза</label>
                <select name="visa" id="id_visa">
                    {% for visa in form_guest.visa %}
                        {{ visa }}
                    {% endfor %}
                </select>

                <label for="id_visa_number">Номер визы</label>
                <input type="text" name="visa_number" id="id_visa_number"
                       autocomplete="off">

                <label for="id_visa_type">Тип визы</label>
                <input type="text" name="visa_type" id="id_visa_type"
                       autocomplete="off">

                <label for="id_visa_given_date">Дата выдачи визы</label>
                <input type="text" name="visa_given_date" id="id_visa_given_date"
                       autocomplete="off">

                <label for="id_visa_expire_date">Дата окончания срока визы</label>
                <input type="text" name="visa_expire_date" id="id_visa_expire_date"
                       autocomplete="off">
            </div>
        </div>
        <a id="send-guest" style="color: #fff;" class="btn btn-primary">Добавить</a>
    </form>
{% endblock %}

{% block scripts %}
    <script src="{% static 'js/guest-add.js' %}"></script>
{% endblock %}

templates/guests/list-guests.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
    <style>
        .pt-3-half {
            padding-top: 1.4rem;
        }
    </style>
{% endblock %}

{% block title %}
    База клиентов
{% endblock %}

{% block content %}

{#    <a href="{% url 'guest-add' %}" class="btn btn-primary btn-sm" style="margin-top: 15px;">Добавить нового клиента</a>#}

    <div class="card">
        <h3 class="card-header text-center font-weight-bold text-uppercase py-4">База гостей</h3>
        <div class="card-body">
            <div id="table" class="table-editable">
<span class="table-add float-right mb-3 mr-2"><a href="#!" class="text-success"><i
        class="fas fa-plus fa-2x" aria-hidden="true"></i></a></span>
                <table class="table table-bordered table-responsive-md table-striped text-center">
                    <thead>
                    <tr>
                        <th class="text-center">Ф.И.О</th>
                        <th class="text-center">Дата рождения</th>
                        <th class="text-center">Сер. номер</th>
                        <th class="text-center">Гражданство</th>
                        <th class="text-center">Телефон</th>
                        <th class="text-center">Email</th>
                        <th class="text-center">Remove</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for guest in guests %}
                        <tr>
                            <td class="pt-3-half" contenteditable="true">{{ guest.full_name }}</td>
                            <td class="pt-3-half" contenteditable="true">{{ guest.date_of_birth }}</td>
                            <td class="pt-3-half" contenteditable="true">{{ guest.serial_number }}</td>
                            <td class="pt-3-half" contenteditable="true">{{ guest.citeznship }}</td>
                            <td>
                                <button type="button" class="btn btn-danger btn-rounded btn-sm my-0">
                                    Save
                                </button>
                            </td>
                            <td class="pt-3-half">
                                <span class="table-up">
                                    <a href="#!" class="indigo-text">
                                        <i class="fas fa-long-arrow-alt-up" aria-hidden="true"></i>
                                    </a>
                                </span>
                                <span class="table-down">
                                    <a href="#!" class="indigo-text">
                                        <i class="fas fa-long-arrow-alt-down" aria-hidden="true"></i>
                                    </a>
                                </span>
                            </td>
                            <td>
                                <span class="table-remove">
                                    <button type="button" class="btn btn-danger btn-rounded btn-sm my-0">
                                        Remove
                                    </button>
                                </span>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>



{#    <table class="table" style="background-color: #fff; color: #505050; margin-top: 15px;">#}
{#        <thead>#}
{#        <tr>#}
{#            <th>ID</th>#}
{#            <th>Имя</th>#}
{#            <th>Телефон</th>#}
{#            <th>Email</th>#}
{#            <th>Номер</th>#}
{#            <th>Заезд</th>#}
{#            <th>Выезд</th>#}
{#            <th>Visa</th>#}
{#            <th>Паспорт</th>#}
{#        </tr>#}
{#        </thead>#}
{#        {% for guest in guests %}#}
{#            <tr>#}
{#                <td>{{ guest.id }}</td>#}
{#                <td>{{ guest.full_name }}</td>#}
{#                <td>{{ guest.phone }}</td>#}
{#                <td>{{ guest.email }}</td>#}
{#                {% for room in guest.booking_set.all %}#}
{#                    {% if forloop.last %}#}
{#                        <td>{{ room.room }}</td>#}
{#                        <td style="font-size: 12px;"#}
{#                            title="{{ room.date_arrival.time }}">{{ room.date_arrival.date }}</td>#}
{#                        <td style="font-size: 12px;"#}
{#                            title="{{ room.date_departure.time }}">{{ room.date_departure.date }}</td>#}
{#                    {% endif %}#}
{#                {% endfor %}#}
{#                <td>{{ guest.visa }}</td>#}
{#                <td>{{ guest.passport }}</td>#}
{#            </tr>#}
{#        {% endfor %}#}
{##}
{#    </table>#}

{% endblock %}

{% block scripts %}
    <script>
        const $tableID = $('#table');
        const $BTN = $('#export-btn');
        const $EXPORT = $('#export');

        const newTr = `
 <tr class="hide">
   <td class="pt-3-half" contenteditable="true">Example</td>
   <td class="pt-3-half" contenteditable="true">Example</td>
   <td class="pt-3-half" contenteditable="true">Example</td>
   <td class="pt-3-half" contenteditable="true">Example</td>
   <td class="pt-3-half" contenteditable="true">Example</td>
   <td class="pt-3-half">
     <span class="table-up"><a href="#!" class="indigo-text"><i class="fas fa-long-arrow-alt-up" aria-hidden="true"></i></a></span>
     <span class="table-down"><a href="#!" class="indigo-text"><i class="fas fa-long-arrow-alt-down" aria-hidden="true"></i></a></span>
   </td>
   <td>
     <span class="table-remove"><button type="button" class="btn btn-danger btn-rounded btn-sm my-0 waves-effect waves-light">Remove</button></span>
   </td>
 </tr>`;

        $('.table-add').on('click', 'i', () => {

            const $clone = $tableID.find('tbody tr').last().clone(true).removeClass('hide table-line');

            if ($tableID.find('tbody tr').length === 0) {

                $('tbody').append(newTr);
            }

            $tableID.find('table').append($clone);
        });

        $tableID.on('click', '.table-remove', function () {

            $(this).parents('tr').detach();
        });

        $tableID.on('click', '.table-up', function () {

            const $row = $(this).parents('tr');

            if ($row.index() === 1) {
                return;
            }

            $row.prev().before($row.get(0));
        });

        $tableID.on('click', '.table-down', function () {

            const $row = $(this).parents('tr');
            $row.next().after($row.get(0));
        });

        // A few jQuery helpers for exporting only
        jQuery.fn.pop = [].pop;
        jQuery.fn.shift = [].shift;

        $BTN.on('click', () => {

            const $rows = $tableID.find('tr:not(:hidden)');
            const headers = [];
            const data = [];

            // Get the headers (add special header logic here)
            $($rows.shift()).find('th:not(:empty)').each(function () {

                headers.push($(this).text().toLowerCase());
            });

            // Turn all existing rows into a loopable array
            $rows.each(function () {
                const $td = $(this).find('td');
                const h = {};

                // Use the headers from earlier to name our hash keys
                headers.forEach((header, i) => {

                    h[header] = $td.eq(i).text();
                });

                data.push(h);
            });

            // Output the result
            $EXPORT.text(JSON.stringify(data));
        });
    </script>
{% endblock %}