AppReception/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from hsm.chess import ChessViews
from hsm.views import EditServicesViews, \
    checks_list, \
    print_booking, \
    organization, \
    add_guest, \
    HomeViews, \
    profile, \
    statistics, \
    TasksViews, \
    GuestsViews, \
    BookingViews, \
    StatusBookingViews, \
    EditBookingViews, \
    DetailBookingViews, \
    user_login, \
    user_logout, \
    user_register, \
    ListBookingViews, \
    printer, \
    ListServicesViews, \
    CreateServicesViews
from hsm.new_chess import NewChessViews

admin.site.site_header = 'Панель управления'
urlpatterns = [
                  path('', HomeViews.as_view(), name='home'),
                  path('chess/', ChessViews.as_view(), name='chess'),
                  path('print/<str:_date>', printer, name='print'),
                  path('admin/', admin.site.urls),
                  path('checks/', checks_list, name='checks-list'),
                  path('login/', user_login, name='login'),
                  path('logout/', user_logout, name='logout'),
                  path('register/', user_register, name='register'),
                  path('booking/', BookingViews.as_view(), name='booking'),
                  path('booking/print-<int:id>', print_booking, name='booking-print'),
                  path('guests/', GuestsViews.as_view(), name='guests'),
                  path('guests/add/', add_guest, name='guest-add'),
                  path('bookings/', ListBookingViews.as_view(), name='list-booking'),
                  path('organization/', organization, name='organization'),
                  path('tasks/', TasksViews.as_view(), name='tasks'),
                  path('statistics/', statistics, name='statistics'),
                  path('services/list', ListServicesViews.as_view(), name='services-list'),
                  path('services/edit-<int:pk>', EditServicesViews.as_view(), name='services-edit'),
                  path('services/create', CreateServicesViews.as_view(), name='services-create'),
                  path('profile/', profile, name='profile'),
                  path('new-chess/', NewChessViews.as_view(), name='new-chess'),
                  path('ajax/', include('hsm.urls'), name='ajax'),
                  path('booking/edit-<int:id>', EditBookingViews.as_view(), name='edit-booking'),
                  path('booking/detail-<int:id>', DetailBookingViews.as_view(), name='detail-booking'),
                  path('booking/status-<int:id>', StatusBookingViews.as_view(), name='status-booking'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hsm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from hsm.ajax import ajax_services_info, ajax_check_print, ajax_bookings_extend, ajax_bookings_change, \
    ajax_search_booking_id, ajax_send_booking_group, ajax_evict_send, ajax_guest_add, ajax_booking_info, ajax_new_chess, \
    ajax_search_rooms, ajax_info_type_rooms, ajax_booking_post, ajax_search_guest, \
    ajax_status_booking_change, ajax_status_booking_remove, ajax_today_date, ajax_cleaning

app_name = 'ajax'
urlpatterns = [
    path('today-date/', ajax_today_date, name='ajax-today-date'),
    path('evict-send/', ajax_evict_send, name='ajax-evict-send'),
    path('cleaning/', ajax_cleaning, name='ajax-cleaning'),
    path('booking-info/', ajax_booking_info, name='ajax-booking-info'),
    path('services-info/', ajax_services_info, name='ajax-services-info'),
    path('bookings-change/', ajax_bookings_change, name='ajax-bookings-change'),
    path('bookings-extend/', ajax_bookings_extend, name='ajax-bookings-extend'),
    path('send-booking-group/', ajax_send_booking_group, name='ajax-send-booking-group'),
    path('search-booking-id/', ajax_search_booking_id, name='ajax-search-booking-id'),
    path('new-chess/', ajax_new_chess, name='ajax-new-chess'),
    path('check-print/', ajax_check_print, name='ajax-check-print'),
    path('status-booking-change/', ajax_status_booking_change, name='ajax-status-booking-change'),
    path('status-booking-remove/', ajax_status_booking_remove, name='ajax-status-booking-remove'),
    path('search-guest/', ajax_search_guest, name='ajax-search-guest'),
    path('booking-post/', ajax_booking_post, name='ajax-booking-post'),
    path('guest-add/', ajax_guest_add, name='ajax-guest-add'),
    path('search-rooms/', ajax_search_rooms, name='ajax-search-rooms'),
    path('info-type-rooms/', ajax_info_type_rooms, name='ajax-info-type-rooms'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hsm/models.py
import arrow
from django.contrib import admin
from django.contrib.auth.models import User
from django.db import models


# Типы номеров
class TypeRoom(models.Model):
    name = models.CharField(verbose_name='Тип комнаты', max_length=50, blank=True)
    price_uzs = models.DecimalField(verbose_name='Цена комнаты для граждан РУЗ', max_digits=8, decimal_places=0,
                                    null=True, blank=True)
    price_usd = models.DecimalField(verbose_name='Цена комнаты для иностранцев', max_digits=8, decimal_places=0,
                                    null=True, blank=True)

    class Meta:
        verbose_name = 'Тип комнаты'
        verbose_name_plural = 'Типы комнат'

    def __str__(self):
        return self.name


# Имя номеров
class Rooms(models.Model):
    type_room = models.ForeignKey(TypeRoom, verbose_name='Тип комнаты', on_delete=models.CASCADE)
    number_room = models.CharField(verbose_name='Номер комнаты', max_length=50, blank=True)
    close = models.BooleanField(verbose_name='Закрыть номер', default=False)
    clean = models.BooleanField(verbose_name='Статус номера', default=True)

    class Meta:
        verbose_name = 'Номер комнаты'
        verbose_name_plural = 'Номера комнат'

    def __str__(self):
        return '%s-%s' % (self.type_room.name, self.number_room)


# Метки
class Tag(models.Model):
    name = models.CharField(verbose_name='Тег', max_length=50)

    class Meta:
        verbose_name_plural = 'Теги'
        verbose_name = 'Тег'

    def __str__(self):
        return self.name


# Страны, города
class City(models.Model):
    name = models.CharField(verbose_name="Город", max_length=50)

    class Meta:
        verbose_name = 'Страна'
        verbose_name_plural = 'Страны'

    def __str__(self):
        return self.name


admin.site.register(City)


# Национальность
class Nationality(models.Model):
    name = models.CharField(verbose_name="Национальность", max_length=50)

    class Meta:
        verbose_name = 'Национальность'
        verbose_name_plural = 'Национальности'

    def __str__(self):
        return self.name


admin.site.register(Nationality)


# Данные визы
class Visa(models.Model):
    number = models.CharField(verbose_name="номер", max_length=50)
    visa_type = models.CharField(verbose_name="тип", max_length=50)
    given_date = models.CharField(verbose_name="Дата выдачи", max_length=30)
    expire_date = models.CharField(verbose_name="Дата окончания срока", max_length=30)

    class Meta:
        verbose_name = 'Виза'
        verbose_name_plural = 'Визы'

    def __str__(self):
        return self.number


admin.site.register(Visa)


# Гражданство
class Citeznship(models.Model):
    name = models.CharField(verbose_name='Гражданство', max_length=50)

    class Meta:
        verbose_name = 'Гражданство'
        verbose_name_plural = 'Гражданства'

    def __str__(self):
        return self.name


# Данные гостя
class Guest(models.Model):
    full_name = models.CharField(verbose_name='Ф.И.О', max_length=100, unique=True)
    phone = models.CharField(verbose_name='Телефон', max_length=50, blank=True)
    email = models.EmailField(verbose_name='Email', max_length=50, blank=True)
    passport = models.BooleanField(verbose_name='Паспорт в наличии', default=True)
    date_of_birth = models.CharField(verbose_name='Дата рождения', max_length=50, blank=True)
    place_of_birth = models.ForeignKey(City, verbose_name="Место рождение: город", on_delete=models.CASCADE, null=True,
                                       blank=True)
    serial_number = models.CharField(verbose_name="Серийный номер паспорта", max_length=50, blank=True)
    given_date = models.CharField(verbose_name="Дата выдачи паспорта", max_length=30, blank=True)
    expire_date = models.CharField(verbose_name="Дата окончания срока паспорта", max_length=30, blank=True)
    give_organization = models.CharField(verbose_name="Кем выдано", max_length=100, blank=True)
    place_of_living = models.CharField(verbose_name="Место проживания", max_length=100, blank=True)
    nationality = models.ForeignKey(Nationality, verbose_name="Национальность", on_delete=models.CASCADE, null=True,
                                    blank=True)
    citeznship = models.ForeignKey(Citeznship, verbose_name="Гражданство", on_delete=models.CASCADE, null=True,
                                   blank=True)
    kpp_number = models.CharField(verbose_name='КПП №', max_length=50, blank=True)
    kpp_date_arrival = models.CharField(verbose_name='Дата заезда КПП', max_length=30, blank=True)
    visa = models.ForeignKey(Visa, verbose_name="VISA", on_delete=models.CASCADE, blank=True, null=True)

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'

    def __str__(self):
        return self.full_name


admin.site.register(Guest)


# Источник откуда поступила бронь
class SourceBooking(models.Model):
    name = models.CharField(verbose_name='Источник бронирования', max_length=50)

    class Meta:
        verbose_name_plural = 'Источники брони'
        verbose_name = 'Источник брони'

    def __str__(self):
        return self.name


admin.site.register(SourceBooking)


# Задачи
class Task(models.Model):
    title = models.CharField(verbose_name='Что сделать', max_length=50, blank=True)
    info = models.TextField(verbose_name='Описание', blank=True)
    # alarm = models.IntegerField(verbose_name='Когда выполнить', null=True, blank=True)
    datetime = models.DateTimeField(verbose_name='Дата и время напоминания', null=True, blank=True)
    status = models.BooleanField(verbose_name='Выполнено', default=False)

    class Meta:
        verbose_name = 'Задача'
        verbose_name_plural = 'Задачи'

    def __str__(self):
        return self.title


admin.site.register(Task)


class Organization(models.Model):
    name = models.CharField(verbose_name='Оргазинация', max_length=100, blank=True)

    class Meta:
        verbose_name = 'Организация'
        verbose_name_plural = 'Организации'

    def __str__(self):
        return self.name


admin.site.register(Organization)


# Информация бронирования
class Booking(models.Model):
    EMPTY = 0
    BOOKING_NOT_PAYMENT = -1
    BOOKING_PAYMENT = 1
    QUEST_ACCOMMODATION_NOT_PAYMENT = -2
    QUEST_ACCOMMODATION_PAYMENT = 2
    EVICTED_ACCOMMODATION = -3
    RESERVE = 3
    GUEST_LEAVE_TODAY = 4
    BLOCKING_ROOM = -4

    STATUS_BOOKING = (
        (EMPTY, 'Пусто'),
        (BOOKING_NOT_PAYMENT, 'Бронь без оплаты'),
        (BOOKING_PAYMENT, 'Бронь с предоплатой'),
        (QUEST_ACCOMMODATION_NOT_PAYMENT, 'Размещение гостя с долгом'),
        (QUEST_ACCOMMODATION_PAYMENT, 'Размещение гостя с оплатой'),
        (EVICTED_ACCOMMODATION, 'Выселенное размещение'),
        (RESERVE, 'Резерв'),
        (GUEST_LEAVE_TODAY, 'Гости сегодня выезжают'),
        (BLOCKING_ROOM, 'Блокировка номера'),
    )

    A = 0
    B = 1
    C = 2
    D = 3
    E = 4
    TYPE_PAYMENT = (
        (A, 'Не известно'),
        (B, 'Наличка'),
        (C, 'Пластик'),
        (D, 'Перечисление'),
        (E, 'В долларах')
    )

    date_arrival = models.DateTimeField(verbose_name='Дата и время заезда', null=True, blank=True)
    early_arrival = models.BooleanField(verbose_name='Ранний заезд', default=False)
    date_departure = models.DateTimeField(verbose_name='Дата и время выезда', null=True, blank=True)
    late_departure = models.BooleanField(verbose_name='Поздник заезд', default=False)
    price_per_night = models.DecimalField(verbose_name='Цена за ночь', max_digits=10, decimal_places=0, default=0)
    price_for_all_time = models.DecimalField(verbose_name='Цена за всё время', max_digits=10, decimal_places=0,
                                             default=0)
    payment_nal = models.DecimalField(verbose_name='Сумма - налом', max_digits=10, decimal_places=0, default=0)
    payment_bez_nal = models.DecimalField(verbose_name='Сумма - перечисление', max_digits=10, decimal_places=0,
                                          default=0)
    payment_terminal = models.DecimalField(verbose_name='Сумма - терминал', max_digits=10, decimal_places=0, default=0)
    payment_usd = models.DecimalField(verbose_name='Сумма - в долларах', max_digits=10, decimal_places=0, default=0)
    paid = models.DecimalField(verbose_name='Оплачено', max_digits=10, decimal_places=0, default=0)
    left_to_pay = models.DecimalField(verbose_name='Осталось оплатить', max_digits=10, decimal_places=0, default=0)
    days = models.FloatField(verbose_name='Суток', null=True, blank=True)
    status_booking = models.IntegerField(verbose_name='Статус брони', choices=STATUS_BOOKING, default=EMPTY)

    user = models.ForeignKey(User, verbose_name='Администратор', on_delete=models.CASCADE, null=True, blank=True)
    guest = models.ManyToManyField(Guest, verbose_name='Проживающие гости', blank=True)
    organization = models.ForeignKey(Organization, verbose_name='Организация', on_delete=models.CASCADE, null=True,
                                     blank=True)
    room = models.ForeignKey(Rooms, verbose_name='Номер остановки', on_delete=models.CASCADE, null=True, blank=True)
    task = models.ForeignKey(Task, verbose_name='Задачи', on_delete=models.CASCADE, null=True, blank=True)
    source_of_booking = models.ForeignKey(SourceBooking, verbose_name='Источник бронирования', on_delete=models.CASCADE,
                                          null=True, blank=True)
    number_source_booking = models.CharField(verbose_name='Номер брони источника', max_length=50, blank=True)
    admin_comment = models.TextField(verbose_name='Комментарий администратора', blank=True)
    customer_wishes = models.TextField(verbose_name='Пожелания гостя', blank=True)

    stat = models.BooleanField(verbose_name='Состояние брони/объекта', default=True)

    class Meta:
        verbose_name = 'Бронь'
        verbose_name_plural = 'Брони'

    def save(self, *args, **kwargs):

templates/booking/edit.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
    <style>
        input {
            padding: 5px;
            font-size: 13px;
            color: #444;
        }

        tbody {
            display: grid;
            grid-template-columns: 1fr 1fr;
            grid-gap: 10px;
        }

        tbody tr {
            display: grid;
            grid-template-columns: 1fr 3fr;
            grid-gap: 10px;
        }
        label {font-size: 14px!important;}
        label[for="id_left_to_pay"] {
            color: red;
        }
        label[for="id_paid"] {
            color: green;
        }
        #id_status_booking[value="-2"] {
            color: green;
        }
    </style>
{% endblock %}

{% block title %}
    EDIT
{% endblock %}

{% block content %}
    <form action="{% url 'edit-booking' booking.id %}" method="post">{% csrf_token %}
        <div class="btns" style="background-color: #fff; padding: 10px; margin-top: 15px;">
            <button type="submit" class="btn btn-primary" name="save" value="home">Сохранить</button>
            <button type="submit" class="btn btn-primary" name="save" value="continue">Сохранить и вернуться</button>
            <a href="/" class="btn btn-primary">Отмена</a>
        </div>
        <table class="table" style="background-color: #fff; color: #505050; padding: 10px;">
            {{ form.as_table }}
        </table>
        <div class="btns" style="background-color: #fff; padding: 10px; margin-top: 15px;">
            <button type="submit" class="btn btn-primary" name="save" value="home">Сохранить</button>
            <button type="submit" class="btn btn-primary" name="save" value="continue">Сохранить и вернуться</button>
            <a href="/" class="btn btn-primary">Отмена</a>
        </div>
    </form>
{% endblock %}

{% block scripts %}
    <script>
        $('#id_guest').select2({width: '100%',});
        $('#id_organization').select2({
            width: 186,
            tags: true
        });
        let selects = ['id_room', 'id_type_payment', 'id_source_of_booking', 'id_status_booking', 'id_task'];

        function fnSelects(selects) {
            for (let i = 0; i < selects.length; i++) {
                $(`#${selects[i]}`).select2({width: 250});
            }
        }

        fnSelects(selects);

        $('#id_admin_comment').css({'width': '100%', 'height': '75px'});
        $('#id_customer_wishes').css({'width': '100%', 'height': '75px'});

    </script>
{% endblock %}

templates/booking/list.html
{% extends 'base.html' %}
{% load static %}
{% load my_filter %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/libs/datatables.min.css' %}">
    <style>
        .block-fixed {
            position: fixed;
            top: 70px;
            right: 10px;
            width: 135px;
        }

        .block-fixed input {
            margin-top: 20px;
            padding-left: 5px;
            width: 100%;
        }

        .block-fixed button {
            font-size: 12px;
            margin-top: 10px;
        }
    </style>
{% endblock %}

{% block title %}
    База клиентов
{% endblock %}

{% block content %}

    <div class="card">
        <h3 class="card-header text-center font-weight-bold text-uppercase py-4">Список всех броней</h3>
        <div class="card-body">

            <div id="table" class="table-editable">
                <div class="d-flex justify-content-center buttons-wrapper flex-wrap pb-3">
                    <button id="" class="btn btn-sm btn-teal btn-rounded addNewColumn">Сменить статус</button>
                    <button id="" class="btn btn-sm btn-teal btn-rounded addNewColumn">Продлить</button>
                    <button id="" class="btn btn-sm btn-mdb-color btn-rounded removeColumns">Удалить бронь
                    </button>
                    <button id="" class="btn btn-sm btn-info btn-rounded addNewRows">Автопродление</button>
                </div>
                <div class="closeByClick d-none"></div>
                <div class="showForm d-none"
                     style="position: fixed; top: 20%; left:50%; transform: translate(-50%, -50%); z-index: 1100;">
                    <form class="text-center border border-light p-5" style="background: white;">
                        <button type="button" class="close position-relative button-x" style="top:-12%; right: -5%">
                            <span aria-hidden="true" class="text-danger">×</span>
                        </button>
                        <h3 class="h3 my-3 text-danger font-weight-bold">Delete</h3>
                        <hr class="mt-2 mb-3">
                        <p class="text-center h5 py-2 pb-3">Are you sure to delete selected rows?</p>
                        <hr class="mt-2 mb-3">
                        <div class="d-flex justify-content-center buttonYesNoWrapper">
                            <button type="button" class="btn btn-danger btnYes btn-sm" data-dismiss="modal">Yes</button>
                            <button type="button" class="btn btn-primary btnNo btn-sm" data-dismiss="modal">No</button>
                        </div>
                    </form>
                </div>

                <table class="table table-bordered table-responsive-md table-striped text-center">
                    <thead>
                    <tr>
                        <th class="text-center"></th>
                        <th class="text-center">ID</th>
                        <th class="text-center">Номер</th>
                        <th class="text-center">Дата заезда</th>
                        <th class="text-center">Дата выезда</th>
                        <th class="text-center">Статус</th>
                        <th class="text-center">Гости</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for booking in bookings %}
                        <tr>
                            <td><input type="checkbox" name="action-selected" value="{{ booking.id }}"
                                       class="action-select"></td>
                            <td><a href="{% url 'edit-booking' booking.id %}">{{ booking.id }}</a></td>
                            <td>{{ booking.room }}</td>
                            <td>{{ booking.date_arrival }}</td>
                            <td>{{ booking.date_departure }}</td>
                            <td class="status{{ booking.status_booking }}">{{ booking.status_booking|status_booking }}</td>
                            <td>
                                {% for guest in booking.guest.all %}
                                    {{ guest }},
                                {% endfor %}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

{#    <div class="block-fixed">#}
{#        <select name="status_booking" id="id_status_booking">#}
{#            <option value="-2">Разместить без оплаты</option>#}
{#            <option value="2">Разместить с оплатой</option>#}
            {#            <option value="-3">Выселить</option>#}
{#        </select>#}
{#        <button class="btn btn-info btn-sm" id="change_status_booking">Изменить статус брони</button>#}
{##}
{#        <input type="number" id="booking_days" value="0">#}
{#        <button class="btn btn-info btn-sm" id="change_date_departure">Продлить дату выезда</button>#}
{#    </div>#}

    {#    <table class="table booking-list" style="background-color: #fff; color: #505050; margin-top: 15px;">#}
    {#        <thead>#}
    {#        <tr>#}
    {#            <th><input type="checkbox" disabled></th>#}
    {#            <th>ID</th>#}
    {#            <th>Номер остановки</th>#}
    {#            <th>Дата заезда</th>#}
    {#            <th>Дата выезда</th>#}
    {#            <th>Статус брони</th>#}
    {#            <th>Гость</th>#}
    {#        </tr>#}
    {#        </thead>#}
    {#        {% for booking in bookings %}#}
    {#            <tr>#}
    {#                <td><input type="checkbox" name="action-selected" value="{{ booking.id }}" class="action-select"></td>#}
    {#                <td><a href="{% url 'edit-booking' booking.id %}">{{ booking.id }}</a></td>#}
    {#                <td>{{ booking.room }}</td>#}
    {#                <td>{{ booking.date_arrival }}</td>#}
    {#                <td>{{ booking.date_departure }}</td>#}
    {#                <td class="status{{ booking.status_booking }}">{{ booking.status_booking|status_booking }}</td>#}
    {#                <td>#}
    {#                    {% for guest in booking.guest.all %}#}
    {#                        {{ guest }},#}
    {#                    {% endfor %}#}
    {#                </td>#}
    {#            </tr>#}
    {#        {% endfor %}#}
    {##}
    {#    </table>#}

{% endblock %}

{% block scripts %}
    <script src="{% static 'js/libs/datatables.min' %}"></script>
    <script>

        $('#dt-more-row-col').mdbEditor({
            modalEditor: true,
            headerLength: 7,
        });
        $('.dataTables_length').addClass('bs-select');

        $('.dataTables_length').addClass('bs-select');

        $('#id_status_booking').select2({
            width: '100%'
        });
        $('#change_status_booking').click(function () {
            let actionSelected = $('.action-select');
            let statusBooking = $('#id_status_booking').val();
            let bookingIDs = [];
            for (let i = 0; i < actionSelected.length; i++) {
                if ($(actionSelected[i]).is(':checked')) {
                    bookingIDs.push($(actionSelected[i]).val());
                }
            }
            if (bookingIDs.length === 0) {
                alert('Вы не выбрали бронь');
            } else {
                $.ajax({
                    url: '/ajax/bookings-change/',
                    method: 'get',
                    data: {
                        statusBooking: statusBooking,
                        bookingIDs: bookingIDs
                    },
                    dataType: 'json',
                    success: function (data) {
                        if (data.ok) window.location.href = '/';
                    }
                })
            }
        });
        $('#change_date_departure').click(function () {
            let days = $('#booking_days').val();
            let actionSelected = $('.action-select');
            let bookingIDs = [];
            for (let i = 0; i < actionSelected.length; i++) {
                if ($(actionSelected[i]).is(':checked')) {
                    bookingIDs.push($(actionSelected[i]).val());
                }
            }
            console.log(days);
            if (days !== 0 && bookingIDs.length !== 0) {
                $.ajax({
                    url: '/ajax/bookings-extend/',
                    method: 'get',
                    data: {
                        days: days,
                        bookingIDs: bookingIDs
                    },
                    dataType: 'json',
                    success: function (data) {
                        if (data.ok) window.location.href = '/';
                    }
                })
            } else {
                console.log(days);
                console.log(bookingIDs);
            }
        });
    </script>
{% endblock %}

templates/booking/status.html
{% extends 'base.html' %}
{% load static %}
{% load my_filter %}

{% block title %}
    Изменения статуса брони {{ booking.id }}
{% endblock %}

{% block content %}
    <div style="opacity: 0;">
        <span id="id_booking_id">{{ booking.id }}</span>
        <span id="current_stat_status_booking">{{ booking.status_booking }}</span>
        <span id="current_stat_type_payment">{{ booking.type_payment }}</span>
        <span id="current_stat_rooms">{{ booking.room }}</span>
        {% for guest in booking.guest.all %}
            <i class="guest_selected" data-guest-id="{{ guest.id }}">{{ guest }}</i>
        {% endfor %}
    </div>

    <table class="table" style="background-color: #fff; padding: 10px; margin-top: 15px;">
        <tbody>
        <tr>
            <td>Имя гостя:</td>

            <td>
                <select name="guests" id="guests" class="js-example-basic-multiple" multiple>
                    {% for guest in guests %}
                        <option value="{{ guest.id }}">{{ guest.full_name }}</option>
                    {% endfor %}
                </select>
            </td>
        </tr>
        <tr>
            <td>Статус брони:</td>

            <td>
                <select name="status_booking" id="id_status_booking">
                    {% for sb in status_booking %}
                        <option value="{{ sb.0 }}">{{ sb.1 }}</option>
                    {% endfor %}
                </select>
            </td>
        </tr>
        <tr>
            <td>Долг:</td>
            <td>{{ booking.left_to_pay }}</td>
        </tr>
        <tr>
            <td>Оплачено:</td>
            <td>
                {{ booking.paid }}
                <input name="paid" id="id_paid" type="number" value="0">
            </td>
        </tr>
        <tr>
            <td>Тип оплаты:</td>

            <td>
                <select name="type_payment" id="id_type_payment">
                    {% for tp in type_payment %}
                        <option value="{{ tp.0 }}">{{ tp.1 }}</option>
                    {% endfor %}
                </select>
            </td>
        </tr>
        <tr>
            <td>Номер</td>

            <td>
                <select name="rooms" id="id_rooms">
                    {% for type_room in type_rooms %}
                        <optgroup label="{{ type_room }}">
                            {% for room in type_room.rooms_set.all %}
                                <option value="{{ room }}">{{ room }}</option>
                            {% endfor %}
                        </optgroup>
                    {% endfor %}
                </select>
            </td>
        </tr>
        <tr>
            <td>Комментарий Админа</td>
            <td>
                <textarea name="admin_comment" id="id_admin_comment" cols="80"
                          rows="5">{{ booking.admin_comment }}</textarea>
            </td>

        </tr>
        <tr>
            <td>Пожелания гостя</td>
            <td>
                <textarea name="customer_wishes" id="id_customer_wishes" cols="80"
                          rows="5">{{ booking.customer_wishes }}</textarea>
            </td>

        </tr>
        </tbody>
    </table>
    <div style="padding: 10px; background-color: #fff; border-radius: 4px;">
        <a class="btn" id="status_save" style="background-color: #505050; color: #fff;">Сохранить</a>
        <a class="btn" id="status_remove" style="background-color: #505050; color: #fff;">Удалить</a>
    </div>

{% endblock %}

{% block scripts %}
    <script src="{% static 'js/status-chess.js' %}"></script>
{% endblock %}